### ISSUE TITLE
默认收起状态下view的高度还是展开时的高度,这是个大问题

### ISSUE THREAD

**Issue by yudongdong12306** [glailton/ExpandableTextView#8]

**Comment by glailton** [comment]
@yudongdong12306 Maybe I did not understand because of the translation to English, but the height in expanble mode depends of the height of the text. In not expandable mode you can use 
expandableTextView:textMode="line"
expandableTextView:collapsedLines="1"

to set the number of lines that should be shown.

If you need send more details.
